### ISSUE TITLE
Keine Verbindung zur Heidelberg

### ISSUE THREAD

**Issue by maxgew** [leuzoe/hdec#1]
Hallo, 

bekomme folgende Fehlermeldung:
`WARNING:hdec:Could not establish modbus connection to id 1; subsequent calls to the device will silently fail - at least next 120 seconds`

- Dip-Switches mehrfach überprüft: S4/4 ON, S6/2 ON, alles andere OFF
- Verkabelung geprüft/durchgemessen, Polung geprüft
- USB-Adapter nennt sich "QinHeng Electronics HL-340 USB-Serial adapter"
Was könnte ich noch checken?

![2022-06-04 13 22 11](https://user-images.githubusercontent.com/106871058/171998684-b814644d-0d92-47c3-b8c3-bc60819848c4.jpg)

Vielen Dank für den Support!

**Comment by leuzoe** [comment]
Hallo maxgew,

zum Adapter kann ich gar nichts sagen, außer vielleicht überflüssigerweise fragen, ob dieser RS-485 "spricht"?
Bei meinen eigenen Tests war tatsächlich das häufigste Problem die falsche Polung der beiden Bus-Adern. 

Den Bus kann man ansonsten noch austesten mit der Diagnose Software aus https://www.modbusdriver.com/diagslave.html. Vielleicht hilft Ihnen diese weiter.

MfG

**Comment by maxgew** [comment]
Hallo leuzoe, 

nach kurzer Recherche scheint es mit dem Adapter häufig Probleme zu geben. 
Welchen Adapter haben Sie genutzt? Hat dieser Plug+Play funktioniert oder muss man noch Baudrate o-Ä. konfigurieren?

VG

**Comment by leuzoe** [comment]
Mein Adapter ist vom Grabbeltisch beim Elektroniker um die Ecke: "no name"...
Baudrate, Parity etc. werden im Programm gesetzt.

**Comment by maxgew** [comment]
Hallo leuzoe, 

heute ist der neue Adapter gekommen - bisher bin ich jedoch nicht erfolgreich. Laut Rezension sogar erfolgreich mit hdec genutzt. 
Zeitweise bekomme ich nachwievor den Fehler "could not establish modbus connection". Beim Einstecken des Fzgs. habe ich in den Logs auch erstmals den Fehler "This may or may not be a Heidelberg..." gesehen. 

Meine Heidelberg ist ein frühes Modell aus KW50/2020, dreistellige SNR.
Könnte es zur Problemen aufgrund möglicher Unterschiede in der ModBus-Tabelle kommen?
Bin mit meinem Latein als Ingenieur langsam am Ende ;-)

**Comment by maxgew** [comment]
Mit Blick zu wbec ist mir dieser Kommentar aufgefallen:

Register 258: Standby Function Control

Read/Write is only possible with Modbus Register-Layouts Version 1.0.8
In 1.0.7, it can only be written. Trying to read will lead to a timeout.

Register 259: Remote Lock

Read/Write is only possible with Modbus Register-Layouts Version 1.0.8
In 1.0.7, it can only be written. Trying to read will lead to a timeout.

Setting register 259 to 0 (in order to remote lock the box) changes the Charging State to 10=F. The box starts then a blink pattern (6x white, 3x blue), which is same as usually for Modbus Timeout.
Conclusion: Don't use Remote Lock. The same function can be reached by setting the current to 0A.

**Comment by leuzoe** [comment]
Hallo maxgew,

das klingt nach einer sehr plausiblen Fehlerursache.

Leider habe ich kein Gerät mehr zur Verfügung, um evtl. Code-Änderungen zu verifizieren.
Wenn Sie noch Geduld haben, können wir versuchen, bei Ihnen auszutesten. Das könnte aber in mehrere Iterationen ausarten.

**Comment by maxgew** [comment]
Hallo leuzoe, 

selbstverständlich habe ich die Geduld. 
Meine Vermutung ist, dass das Problem vom Lesen des Remote Lock herrührt.

**Comment by leuzoe** [comment]
Hallo maxgew,

ich habe jetzt eine in Bezug auf die Register 258 und 259 geänderte Version eingestellt.
Leider bin ich ziemlich schlecht darin, "blind" (also ohne Tests) zu programmieren. Das müssten jetzt bitte Sie übernehmen :-(

**Comment by maxgew** [comment]
Das war eindeutig zu tief gestapelt. Die neue Version funktioniert auf den ersten Versuch fehlerfrei. 
Chapeau! Besten Dank für den sehr agilen Support, leuzoe!

**Comment by maxgew** [comment]
Nächste Woche geht die PV ans Netz. 
Ich berichte, sollte es noch offene Punkte geben.

**Comment by leuzoe** [comment]
Freut mich, dass es geklappt hat.
Danke im Übrigen auch für die Recherche in Bezug auf die Modbus Versionen.

**Comment by maxgew** [comment]
Okay, erster Dämpfer kommt leider Früher als gedacht:
Der hdec service rennt nach 1-3 Minuten in einen Timeout, Webserver nicht mehr erreichbar. 
Nach Service Restart funktioniert alles wieder tadellos. 

Jun 08 19:19:43 raspberrypi systemd[1]: Started hdec.
Jun 08 19:38:12 raspberrypi python3[469]: ----------------------------------------
Jun 08 19:38:12 raspberrypi python3[469]: Exception happened during processing of request from ('127.0.0.1', 51340)
Jun 08 19:38:12 raspberrypi python3[469]: Traceback (most recent call last):
Jun 08 19:38:12 raspberrypi python3[469]:   File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
Jun 08 19:38:12 raspberrypi python3[469]:     self.process_request(request, client_address)
Jun 08 19:38:12 raspberrypi python3[469]:   File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
Jun 08 19:38:12 raspberrypi python3[469]:     self.finish_request(request, client_address)
Jun 08 19:38:12 raspberrypi python3[469]:   File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
Jun 08 19:38:12 raspberrypi python3[469]:     self.RequestHandlerClass(request, client_address, self)
Jun 08 19:38:12 raspberrypi python3[469]:   File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
Jun 08 19:38:12 raspberrypi python3[469]:     self.handle()
Jun 08 19:38:12 raspberrypi python3[469]:   File "/usr/lib/python3.7/http/server.py", line 426, in handle
Jun 08 19:38:12 raspberrypi python3[469]:     self.handle_one_request()
Jun 08 19:38:12 raspberrypi python3[469]:   File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
Jun 08 19:38:12 raspberrypi python3[469]:     method()
Jun 08 19:38:12 raspberrypi python3[469]:   File "/var/www/hdec/hdecserver.py", line 63, in do_GET
Jun 08 19:38:12 raspberrypi python3[469]:     self.wb.allowed(cmd[1] == "0")
Jun 08 19:38:12 raspberrypi python3[469]: AttributeError: 'wallbox' object has no attribute 'allowed'
Jun 08 19:38:12 raspberrypi python3[469]: ----------------------------------------
Jun 08 19:38:12 raspberrypi python3[469]: Exception happened during processing of request from ('127.0.0.1', 51354)
Jun 08 19:38:12 raspberrypi python3[469]: Traceback (most recent call last):
Jun 08 19:38:12 raspberrypi python3[469]:   File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
Jun 08 19:38:12 raspberrypi python3[469]:     self.process_request(request, client_address)
Jun 08 19:38:12 raspberrypi python3[469]:   File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
Jun 08 19:38:12 raspberrypi python3[469]:     self.finish_request(request, client_address)
Jun 08 19:38:12 raspberrypi python3[469]:   File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
Jun 08 19:38:12 raspberrypi python3[469]:     self.RequestHandlerClass(request, client_address, sel

**Comment by leuzoe** [comment]
Hallo maxgew,
nutzen Sie das Modul im Zusammenhang mit openwb?
Ganz offenkundig sind Sie auf einen (Tipp-)Fehler gestoßen, der bislang nicht aufgefallen ist. Da er in einer Funktion vorkommt, die openwb wohl nicht anspricht, war das bislang nicht aufgefallen.
Ich habe den Fehler korrigiert. Schauen Sie mal, ob es jetzt besser läuft. Irritieren tut mich dabei allerdings die Aussage, dass es nach 1-3 Minuten zum Fehler kommt, sodass ich nur bedingt hoffnungsvoll bin. Wenn's nicht läuft, müssen wir halt weitere Fehlerquellen identifizieren und ausschalten.

**Comment by maxgew** [comment]
Hallo leuzoe, 
ja genau, nutze hdec zsm. mit openWB. 

Hier der Log dazu:

> -- Logs begin at Thu 2019-02-14 11:11:59 CET, end at Thu 2022-06-09 11:40:21 CEST. --
> Jun 09 11:35:47 raspberrypi systemd[1]: Started hdec.
> Jun 09 11:40:18 raspberrypi python3[471]: ----------------------------------------
> Jun 09 11:40:18 raspberrypi python3[471]: Exception happened during processing of request from ('192.168.188.21', 51849)
> Jun 09 11:40:18 raspberrypi python3[471]: Traceback (most recent call last):
> Jun 09 11:40:18 raspberrypi python3[471]:   File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
> Jun 09 11:40:18 raspberrypi python3[471]:     self.process_request(request, client_address)
> Jun 09 11:40:18 raspberrypi python3[471]:   File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
> Jun 09 11:40:18 raspberrypi python3[471]:     self.finish_request(request, client_address)
> Jun 09 11:40:18 raspberrypi python3[471]:   File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
> Jun 09 11:40:18 raspberrypi python3[471]:     self.RequestHandlerClass(request, client_address, self)
> Jun 09 11:40:18 raspberrypi python3[471]:   File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
> Jun 09 11:40:18 raspberrypi python3[471]:     self.handle()
> Jun 09 11:40:18 raspberrypi python3[471]:   File "/usr/lib/python3.7/http/server.py", line 426, in handle
> Jun 09 11:40:18 raspberrypi python3[471]:     self.handle_one_request()
> Jun 09 11:40:18 raspberrypi python3[471]:   File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
> Jun 09 11:40:18 raspberrypi python3[471]:     method()
> Jun 09 11:40:18 raspberrypi python3[471]:   File "/var/www/hdec/hdecserver.py", line 50, in do_GET
> Jun 09 11:40:18 raspberrypi python3[471]:     data = self.wb.status_as_goe()
> Jun 09 11:40:18 raspberrypi python3[471]:   File "/var/www/hdec/heidelberg.py", line 221, in status_as_goe
> Jun 09 11:40:18 raspberrypi python3[471]:     self._get_client_registers(force=True)
> Jun 09 11:40:18 raspberrypi python3[471]:   File "/var/www/hdec/heidelberg.py", line 300, in _get_client_registers
> Jun 09 11:40:18 raspberrypi python3[471]:     self._upd_registers(r,   1, 18)
> Jun 09 11:40:18 raspberrypi python3[471]:   File "/var/www/hdec/heidelberg.py", line 325, in _upd_registers
> Jun 09 11:40:18 raspberrypi python3[471]:     a = self.wb.read_registers(start, num, functioncode)
> Jun 09 11:40:18 raspberrypi python3[471]:   File "/usr/local/lib/python3.7/dist-packages/minimalmodbus.py", line 908, in read_registers
> Jun 09 11:40:18 raspberrypi python3[471]:     payloadformat=_Payloadformat.REGISTERS,
> Jun 09 11:40:18 raspberrypi python3[471]:   File "/usr/local/lib/python3.7/dist-packages/minimalmodbus.py", line 1245, in _generic_command
> Jun 09 11:40:18 raspberrypi python3[471]:     payload_from_slave = self._perform_command(functioncode, payload_to_slave)
> Jun 09 11:40:18 raspberrypi python3[471]:   File "/usr/local/lib/python3.7/dist-packages/minimalmodbus.py", line 1322, in _perform_command
> Jun 09 11:40:18 raspberrypi python3[471]:     response_bytes = self._communicate(request_bytes, number_of_bytes_to_read)
> Jun 09 11:40:18 raspberrypi python3[471]:   File "/usr/local/lib/python3.7/dist-packages/minimalmodbus.py", line 1490, in _communicate
> Jun 09 11:40:18 raspberrypi python3[471]:     raise NoResponseError("No communication with the instrument (no answer)")
> Jun 09 11:40:18 raspberrypi python3[471]: minimalmodbus.NoResponseError: No communication with the instrument (no answer)
> Jun 09 11:40:18 raspberrypi python3[471]: ----------------------------------------


> Jun 09 11:40:24 raspberrypi python3[471]: Exception happened during processing of request from ('192.168.188.21', 51855)
Jun 09 11:40:24 raspberrypi python3[471]: Traceback (most recent call last):
Jun 09 11:40:24 raspberrypi python3[471]:   File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
Jun 09 11:40:24 raspberrypi python3[471]:     self.process_request(request, client_address)
Jun 09 11:40:24 raspberrypi python3[471]:   File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
Jun 09 11:40:24 raspberrypi python3[471]:     self.finish_request(request, client_address)
Jun 09 11:40:24 raspberrypi python3[471]:   File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
Jun 09 11:40:24 raspberrypi python3[471]:     self.RequestHandlerClass(request, client_address, self)
Jun 09 11:40:24 raspberrypi python3[471]:   File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
Jun 09 11:40:24 raspberrypi python3[471]:     self.handle()
Jun 09 11:40:24 raspberrypi python3[471]:   File "/usr/lib/python3.7/http/server.py", line 426, in handle
Jun 09 11:40:24 raspberrypi python3[471]:     self.handle_one_request()
Jun 09 11:40:24 raspberrypi python3[471]:   File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
Jun 09 11:40:24 raspberrypi python3[471]:     method()
Jun 09 11:40:24 raspberrypi python3[471]:   File "/var/www/hdec/hdecserver.py", line 79, in do_GET
Jun 09 11:40:24 raspberrypi python3[471]:     self._process_pi, fd.read())
Jun 09 11:40:24 raspberrypi python3[471]:   File "/usr/lib/python3.7/re.py", line 192, in sub
Jun 09 11:40:24 raspberrypi python3[471]:     return _compile(pattern, flags).sub(repl, string, count)
Jun 09 11:40:24 raspberrypi python3[471]:   File "/var/www/hdec/hdecserver.py", line 90, in _process_pi
Jun 09 11:40:24 raspberrypi python3[471]:     return(str(eval(m)))
Jun 09 11:40:24 raspberrypi python3[471]:   File "<string>", line 1, in <module>
Jun 09 11:40:24 raspberrypi python3[471]:   File "/var/www/hdec/heidelberg.py", line 175, in get_logistic_string
Jun 09 11:40:24 raspberrypi python3[471]:     self._get_client_registers()
Jun 09 11:40:24 raspberrypi python3[471]:   File "/var/www/hdec/heidelberg.py", line 300, in _get_client_registers
Jun 09 11:40:24 raspberrypi python3[471]:     self._upd_registers(r,   1, 18)
Jun 09 11:40:24 raspberrypi python3[471]:   File "/var/www/hdec/heidelberg.py", line 325, in _upd_registers
Jun 09 11:40:24 raspberrypi python3[471]:     a = self.wb.read_registers(start, num, functioncode)
Jun 09 11:40:24 raspberrypi python3[471]:   File "/usr/local/lib/python3.7/dist-packages/minimalmodbus.py", line 908, in read_registers
Jun 09 11:40:24 raspberrypi python3[471]:     payloadformat=_Payloadformat.REGISTERS,
Jun 09 11:40:24 raspberrypi python3[471]:   File "/usr/local/lib/python3.7/dist-packages/minimalmodbus.py", line 1245, in _generic_command
Jun 09 11:40:24 raspberrypi python3[471]:     payload_from_slave = self._perform_command(functioncode, payload_to_slave)
Jun 09 11:40:24 raspberrypi python3[471]:   File "/usr/local/lib/python3.7/dist-packages/minimalmodbus.py", line 1322, in _perform_command
Jun 09 11:40:24 raspberrypi python3[471]:     response_bytes = self._communicate(request_bytes, number_of_bytes_to_read)
Jun 09 11:40:24 raspberrypi python3[471]:   File "/usr/local/lib/python3.7/dist-packages/minimalmodbus.py", line 1490, in _communicate
Jun 09 11:40:24 raspberrypi python3[471]:     raise NoResponseError("No communication with the instrument (no answer)")
Jun 09 11:40:24 raspberrypi python3[471]: minimalmodbus.NoResponseError: No communication with the instrument (no answer)

**Comment by leuzoe** [comment]
Das klingt irgendwie verdächtig nach der Standby Funktion der Box.
Betroffen ist das Register 258, was ja bei Ihnen leider nicht ausgelesen werden kann.
Vielleicht hilft eine Version, in der dieses Register komplett unangetastet bleibt. Ich melde mich, wenn es was Neues gibt.

**Comment by leuzoe** [comment]
Ich habe jetzt noch ein wenig um die Standby-Funktion herum gewerkelt. Wenn das weiterhin nicht hilft, komme ich ohne eine eigene Box nicht mehr aus. Aber testen Sie gerne noch einmal...

**Comment by maxgew** [comment]
Es läuft und läuft und läuft. 
Vielen Dank nochmals für den herausragenden Support!

**Comment by leuzoe** [comment]
Freut mich.
Dann wünsche ich "gutes Überschuss-Laden", wenn die PV Anlage installiert ist. 

Falls dazu Interessantes auszutauschen ist, wäre vielleicht der Weg über persönliche Nachrichten im openWB Forum geeignet.
