### ISSUE TITLE
hdec in evcc

### ISSUE THREAD

**Issue by helix0712** [leuzoe/hdec#3]
Hi, i tried to use hdec in evcc but ran into one issue.

According to the go-echarger API documentation on github the NRG json object has to hold numeric values but no strings.
EVCC is unable to parse these string vales (like OpneWB seems to be able to) and fails with an error message.
I made a quick change in heidelberg.py ->    def status_as_goe(self): -> lines 257 to 274:
I changed:
            "nrg": (
                "{}".format(self.get_voltage(1)),
                "{}".format(self.get_voltage(2)),
                "{}".format(self.get_voltage(3)),
                "0",
                "{}".format(self.get_current(1) * 10),
                "{}".format(self.get_current(2) * 10),
                "{}".format(self.get_current(3) * 10),
                "{:.1f}".format(self.get_voltage(1) * self.get_current(1) / 100),
                "{:.1f}".format(self.get_voltage(2) * self.get_current(2) / 100),
                "{:.1f}".format(self.get_voltage(3) * self.get_current(3) / 100),
                "0",
                "{:.1f}".format(self.get_power() * 100),
                "1",
                "1",
                "1",
                "1",
                )
to:
            "nrg": (
                self.get_voltage(1),
                self.get_voltage(2),
                self.get_voltage(3),
                0,
                (self.get_current(1) * 10),
                (self.get_current(2) * 10),
                (self.get_current(3) * 10),
                (self.get_voltage(1) * self.get_current(1) / 100),
                (self.get_voltage(2) * self.get_current(2) / 100),
                (self.get_voltage(3) * self.get_current(3) / 100),
                0,
                (self.get_power() * 100),
                1,
                1,
                1,
                1,
                )

so that only numeric values are presented.

Wanted to leave a note, as your solution better suits my needs and i do not need to install another ESP8266 like in steff393's solution.

Many thanks for your work!

Patrick

**Comment by leuzoe** [comment]
Interesting. I don't know nothing about EVCC but I'm happy to hear that hdec is applicable in other environments beside openWB.

I'm not sure whether your modification would break communication with openWB, so I won't change the code but leave a note within the module so other may benefit from your finding.

Thanks anyway for your input.

**Comment by oldgitdaddy** [comment]
BTW: to run it in EVCC, I had to change temperature to INT using round().
