### ISSUE TITLE
Stable 1.9.271 - Probleme mit Stop/Standby

### ISSUE THREAD

**Issue by maxgew** [leuzoe/hdec#4]
Seit der OpenWB Stable 1.9.271 habe ich Probleme, dass die Ladung im PV-Modus, aber auch manuell, nicht mehr stoppt. 
Laut Changelog gab es eine Anpassung i.V.m. Go-e Charger:
"Go-e: keine Aktualisierung senden, wenn der Sollstrom 0A ist"

![image](https://user-images.githubusercontent.com/106871058/184722800-46565f57-168d-4915-a4c0-512b062cdd08.png)

**Comment by oldgitdaddy** [comment]
Habe ein ähnliches Problem mit der EVCC integration gehabt. Habe es in meinem fork gelöst. Siehe hier:
[https://github.com/oldgitdaddy/hdec/blob/main/src/heidelberg.py#L84-L88](https://github.com/oldgitdaddy/hdec/blob/main/src/heidelberg.py#L84-L88)
